server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://shortline.proxy.rlwy.net:50438/railway
    username: postgres
    password: XQnkiQzohkpozySKKhRULBhZgfJDENhu
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
